### ISSUE TITLE
Several issues with zoneminder 1.30

### ISSUE THREAD

**Issue by jeroenst** [cassandra/arc-console#3]
In the mainview I see this error on the left site in the middle:

SQL-ERR 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '296''' at line 1', statement was 'select E.*,M.Name as MonitorName,M.Width,M.Height,M.DefaultRate,M.DefaultScale from Events as E inner join Monitors as M on E.MonitorId = M.Id where E.Id = ''296'''

When I click on a camera I get this error instead of the livestream:

SQL-ERR 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1''' at line 1', statement was 'select C.*, M.* from Monitors as M left join Controls as C on (M.ControlId = C.Id ) where M.Id = ''1'''

**Comment by jeroenst** [comment]
This is because  E.id and M.Id are not having " but ' around it's value in sql statement...

**Comment by jeroenst** [comment]
After I fixed this, the event monitor works, but when selecting an input I get a broken image icon..

**Comment by Megaten-NZ** [comment]
How did you fix it? I changed " to ' but still had similar issue. Also buttons missing text. E.g.
div id="arc-live-button-ALL" class="arc-live-monitor-control arc-button" state="active" onclick="ARC_handleLiveNameClick( 'ALL' );" title=""></div

**Comment by brononius** [comment]
What I've done to get it working:

Line 35 in /usr/share/zoneminder/www/skins/arc/views/arc-watch.php
```
$sql = "select C.*, M.* from Monitors as M left join Controls as C on (M.ControlId = C.Id ) where M.Id = ''.dbEscape($_REQUEST['mid']).''";
```

Line 41 in /usr/share/zoneminder/www/skins/arc/views/arc-event.php
```
$sql = "select E.*,M.Name as MonitorName,M.Width,M.Height,M.DefaultRate,M.DefaultScale from Events as E inner join Monitors as M on E.MonitorId = M.Id where E.Id = ".dbEscape($eid)."".$midSql;
```

**Comment by jeroenst** [comment]
Reinstalled from ubuntu repository.. No problem anymore.
